services:
  jupyter:
    container_name: jupyter
    build: .
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work